---
- name: Remove Gcsfuse repository file if it exists
  ansible.builtin.file:
    path: /etc/yum.repos.d/gcsfuse.repo
    state: absent
  become: yes

- name: Install Gcsfuse build dependencies
  package:
    name:
    - fuse
    - git
    - golang
    state: present
    update_cache: yes
  become: yes

- name: Clone Gcsfuse repository
  git:
    repo: https://github.com/GoogleCloudPlatform/gcsfuse.git
    dest: /tmp/gcsfuse
    version: master
    force: yes
  become: yes

- name: Create GOPATH directory
  file:
    path: "/root/go"
    state: directory
    mode: '0755'
  become: yes

- name: Install Gcsfuse via go install
  command:
    cmd: go install .
    chdir: /tmp/gcsfuse
  become: yes
  environment:
    GOPATH: "/root/go"

- name: Symlink Gcsfuse binary to /usr/local/bin
  file:
    src: /root/go/bin/gcsfuse
    dest: /usr/local/bin/gcsfuse
    state: link
    force: yes
  become: yes
