---

- name: Check PMIx OS Compatibility
  assert:
    that: not ( install_pmix and ansible_distribution == "CentOS" and ansible_distribution_major_version|int
      <= 7 )
    msg: PMIx is not available on CentOS 7

- name: Include OS Family Dependent Vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
  - files:
    - '{{ ansible_distribution|lower }}-{{ ansible_distribution_version }}.yml'
    - '{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_distribution|lower }}.yml'
    - '{{ ansible_os_family|lower }}-{{ ansible_distribution_version }}.yml'
    - '{{ ansible_os_family|lower }}-{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_os_family|lower }}.yml'
    skip: true

- name: Wait for DPKG Locks
  ansible.builtin.shell: >
    while fuser /var/lib/dpkg/{{ item }} >/dev/null 2>&1; do
      sleep 5
    done
  with_items:
  - lock
  - lock-frontend
  when:
  - ansible_os_family == 'Debian'

- name: Install PMIx libraries and headers
  ansible.builtin.package:
    name: '{{ pmix_packages }}'
    state: present
