# Copyright 2021 SchedMD LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Install Aptitude
  apt:
    name: 
      - aptitude
      - software-properties-common
    state: present

- name: Wait for APT Lock
  shell: while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;

- name: Upgrade {{ansible_os_family}} Family System Software
  apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Install {{ansible_os_family}} Family Development Dependencies
  apt:
    name:
      - build-essential
      - doxygen
      - g++
      - libssl-dev
      - pkg-config
    state: present

- name: Install {{ansible_os_family}} Family Misc. Software
  package:
    name:
      - iputils-ping
    state: present
