imports:
- path: schedmd-slurm-gcp.jinja

resources:
- name: schedmd-slurm-gcp
  type: schedmd-slurm-gcp.jinja
  properties:
    cluster_name: slurmtest
    zone: us-central1-b
    login_node_count: 1
    compute_static_node_count: 1
