---
# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

pmix_version: 4.2.9
pmix_dir: pmix-{{ pmix_version }}
pmix_tar: '{{ pmix_dir }}.tar.gz'
pmix_url: https://github.com/openpmix/openpmix/releases/download/v{{ pmix_version }}/{{ pmix_tar }}
# This is set separate from path.installation as slurm searches /usr and /usr/local for pmix
pmix_installation_path: /usr/local
