---
# tasks file for ansible-role-cuda
- name: Trust packaging key for Nvidia repositories (apt)
  apt_key:
    data: "{{ lookup('file', 'files/nvidia_packaging_key.asc') }}"
    id: "{{ cuda_packaging_key_id }}"
    state: present

- name: Configure Nvidia repository (apt)
  apt_repository:
    repo: "deb {{ cuda_repo_url }}/{{ cuda_repo_subfolder }}/x86_64 /"
    filename: nvidia
    state: present

# vim:ft=ansible:
