---
# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Check if pyxis is installed
  stat:
    path: /usr/local/lib/slurm/spank_pyxis.so
  register: pyxis_installed

- block:
  - name: Clone pyxis
    ansible.builtin.git:
      repo: 'https://github.com/NVIDIA/pyxis.git'
      dest: /tmp/pyxis
      version: 'v{{ pyxis_ver }}'

  - name: Build and install pyxis
    ansible.builtin.shell:
      cmd: make install
      chdir: /tmp/pyxis

  - name: Add line to plugstack conf
    ansible.builtin.lineinfile:
      create: True
      path: /etc/slurm/plugstack.conf
      regexp: '\s*required\s+/usr/local/lib/slurm/spank_pyxis.so\s*'
      line: 'required /usr/local/lib/slurm/spank_pyxis.so'
  when: not pyxis_installed.stat.exists
