#!/bin/bash
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Slurm Epilog for NVIDIA Imex

set -ex

if ! systemctl list-unit-files --all | grep -Fq "nvidia-imex.service"; then
    exit 0
fi

# Clean the config file in case the service gets started by accident
> /etc/nvidia-imex/nodes_config.cfg

NVIDIA_IMEX_STOP_TIMEOUT=30

# clean up connection
set +e

timeout $NVIDIA_IMEX_STOP_TIMEOUT systemctl stop nvidia-imex

pkill -9 nvidia-imex
set -e
